<div class="row">
    <div class="cell" > 
        <div class="dashhead">Top Violations by Dealer</div>

        <table class="Dash" >
            <tr >
                <td width="150">Dealer</td>	
                <td>No. of current violations</td>
                <td>No. of previous violations</td>
                <td>%</td>
            </tr>
            <?php
             $i = 0;
            foreach ($newArray as $dash) {
                $diffr = ($dash['countcurrent'] - $dash['countprev']);
                $csum = ($dash['countcurrent'] + $dash['countprev']);
                if ($i > 7)
                        break;
                    else{
                $avg = ($csum) / 2;
                $percent = ($diffr / $avg) * 100;
                echo "<tr>";
                echo "<td>";
                if ($diffr < 0)
                    $x = "green";
                elseif ($diffr == 0)
                    $x = "black";
                elseif ($diffr > 0)
                    $x = "red";
                echo "<a href=" . "index.php?tab=violations-history&website_id=" . $dash['website_id'] . "&wname=" . $dash['name'] . ">" . $dash['name'] . "</td>" . "<td>" . $dash['countcurrent'] . " (" . "<font color=" . "$x" . ">" . ($diffr > 0 ? "+" : "") . $diffr . "</font>" . ")" . "</td>" . "<td>" . $dash['countprev'] . "</td>" . "<td>" . "<font color=" . "$x" . ">" . ($diffr > 0 ? "+" : "") . round($percent, 2) . "%" . "</font>" . "</tr>";
                echo "</td>";
                echo "</tr>";
                $i++;
                    }
                }
            echo "</table>";
            ?>
          <table class="Dash" ><tr><td width="500"><a href="index.php?tab=violations-history" >Show All<a/></td></tr></table>
    </div>
    <div class="cell" >
        <div class="dashhead">Top violations by SKU</div>

        <table class="Dash" >
            <tr>
                <td width="150">SKU</td>	
                <td >No. of current violations</td>
                <td >No. of Previous violations</td>
            </tr>
            <?php
             $i = 0;
            foreach ($viosku as $das) {
                $diffr = ($das['currentcount'] - $das['prevcount']);
                $csum = ($das['currentcount'] + $das['prevcount']);
                if ($i > 7)
                        break;
                    else{

                echo "<tr>";
                echo "<td>";
                if ($diffr < 0)
                    $x = "green";
                elseif ($diffr == 0)
                    $x = "black";
                elseif ($diffr > 0)
                    $x = "red";
                echo "<a href=" . "index.php?tab=violations-history&product_id=" . $das['product_id'] . "&sku=" . $das['sku1'] . ">" . $rnm = $das['sku1'] . "</td>" . "<td>" . $das['currentcount'] . " (" . "<font color=" . "$x" . ">" . ($diffr > 0 ? "+" : "") . $diffr . "</font>" . ")" . "</td>" . "<td>" . $das['prevcount'] . "</td>" . "</tr>";
                echo "</td>";
                echo "</tr>";
                $i++;
            }
            }
            echo "</table>";
            ?>
<table class="Dash" ><tr><td width="500"><a href="index.php?tab=violations-history" >Show All<a/></td></tr></table>
    </div>
</td>
<div class="cell" >         
    <div class="dashhead">SKU by violation amt</div>

    <table class="Dash" width="250">
        <tr>

            <td width="170">SKU</td>
            <td >Violation Amount</td>

        </tr>
        <?php
        foreach ($dash1_array as $dash2) {
            echo "<tr>";
            echo "<td>";
            echo "<a>" . $dash2->sku . "</td>" . "<td>$" . $dash2->violation_amount . "</td>" . "</tr>";
        }

        echo "</table>";
        ?>
        <table class="Dash" ><tr><td width="237"><a href="index.php?tab=violations-history" >Show All<a/></td></tr></table>
</div>

<div class="cell"  style="height:200px;width:190px;" > 
    <div class="dashhead" style="visibility:hidden" >SKU</div>

    <table class="Dash">
        <tr> 
            <td width="250">Stopped Violations SKU</td>
        </tr>					
        <?php
        $i = 0;
        if (count($resultst) == 0)
            echo "<tr align=" . "center" . ">" . "<td>No New SKU Violated</td>" . "</tr>";
        else {
            forEach ($resultst as $key => $value) {
                if ($i > 2)
                    break;
                else {
                    echo "<tr>";
                    echo "<td>";
                    echo $value;
                    echo "</td>";
                    echo "</tr>";
                    $i++;
                }
            }
        }
        echo "</table>";
        ?>
        </td>
        <div class="dashhead" style="visibility:hidden" >SKU</div>

        <table class="Dash">
            <tr> 
                <td width="250">Started Violations SKU</td>
            </tr>					
            <?php
            $i = 0;
            if (count($resultstrt) == 0)
                echo "<tr align=" . "center" . ">" . "<td>No New SKU's Violated</td>" . "</tr>";
            else {
                forEach ($resultstrt as $key => $value) {
                    if ($i > 2)
                        break;
                    else {
                        echo "<tr>";
                        echo "<td>";
                        echo $value;
                        echo "</td>";
                        echo "</tr>";
                        $i++;
                    }
                }
            }
            echo "</table>";
            ?>
            </td>
            </div>
            <div class="cell"  style="height:200px;width:190px;" > 
                <div class="dashhead" style="visibility:hidden" >Dealer</div>

                <table class="Dash">
                    <tr> 
                        <td width="250">Stopped Violations Dealer</td>
                    </tr>					
                    <?php
                    $i = 0;
                    if (count($resultstv) == 0)
                        echo "<tr align=" . "center" . ">" . "<td>No New Dealers Violated</td>" . "</tr>";
                    else {
                        forEach ($resultstv as $key => $value) {
                            if ($i > 2)
                                break;
                            else {
                                echo "<tr>";
                                echo "<td>";
                                echo $value;
                                echo "</td>";
                                echo "</tr>";
                                $i++;
                            }
                        }
                    }
                    echo "</table>";
                    ?>
                    </td>

                    <div class="dashhead" style="visibility:hidden" >Dealer</div>

                    <table class="Dash">
                        <tr> 
                            <td width="250">Started Violations Dealer</td>	
                        </tr>					
                        <?php
                        $i = 0;
                        if (count($resultstrtv) == 0)
                            echo "<tr align=" . "center" . ">" . "<td>No New Dealers Violated</td>" . "</tr>";
                        else {
                            forEach ($resultstrtv as $key => $value) {
                                if ($i > 3)
                                    break;
                                else {
                                    echo "<tr>";
                                    echo "<td>";
                                    echo $value;
                                    echo "</td>";
                                    echo "</tr>";
                                    $i++;
                                }
                            }
                        }
                        echo "</table>";
                        ?>
                        </td>
                        </div> 

                        <table>
                            <tr><td>
                                    <div class="cell" align="center" > 
                                        <div class="cell" align="center" style="float: left;width: 600px; margin: 0 auto;" > 
                                             <?php include_once 'charts/a1.php'; ?>
                                        </div>
                                        <div class="cell" align="center" style="float: right;width: 600px; margin: 0 auto;" > 
                                            <?php include_once 'charts/a2.php'; ?>
                                        </div>
                                    </div></td></tr>
                            <tr><td>
                                    <div> 
                                        <?php include_once 'charts/a7.php'; ?>
                                    </div></td>
                            </tr></table>

                        </div>



