<?php
include_once 'db_login.php';
include_once 'db_class.php';
include_once './toMoney.php';
$db_resource = new DB ();
//$em = $_SESSION['email'];

$em = (isset($_SESSION['email']) ? $_SESSION['email'] : "");
$fetch = "select username from admin_users where email='$em'";
$products = $db_resource->GetResultObj($fetch);

if (count($products) > 0) {
    $us = $products[0]->username;
}

if (isset($_SESSION ['username'])) {
    $user_info = "Welcome " . $us . ",<a href=\"login.php?action=logout\"> Logout</a>";
} else {
    $user_info = "Welcome Guest! <a href=\"login.php\"> Sign In!</a>";
}
?>


<div id="kraus_header_wrapper">
    <div id="kraus_header">
        <div class="header-logo container" >
            <div class="logo-img">
                <a href="/"  ><img src="images/Kraus-Logo-HQ.png" width="186" height="71" /> </a>
            </div>
            <div class="logo-text" >Price Defender</div>
        </div>
        <div class="menu-container container">
            <div class="menu-item  first">  
                <?php if (isset($_SESSION ['username'])) { ?>
                    <a href="index.php"  class="top-menu-item-3"> Home </a>
                <?php } ?>
            </div>		
            <div class="menu-item second" >
                <?php if (isset($_SESSION ['username'])) { ?>
                    <a href="mysettings.php" class="top-menu-item-3"> Settings</a>
                <?php } ?>
            </div>			
            <div class="menu-item third" >  
                <?php if (isset($_SESSION ['role']) && $_SESSION ['role'] === 'Admin') { ?>
                    <a href="websites.php" class="top-menu-item-3" > Websites </a>
                <?php } ?>
            </div>

            <div class="menu-item fourth">  
                <?php if (isset($_SESSION ['role']) && $_SESSION ['role'] === 'Admin') { ?>
                    <a href="users.php"  class="top-menu-item-3"> users </a>
                <?php } ?>
            </div>

            <div class="user-container container" >
                <div class="img-part"><img src="images/agent.png" width="28" height="24" /></div> 
                <div class="text-part">  <?php echo $user_info; ?> </div> 
            </div>
        </div>
    </div>
</div>
