<script type="text/javascript">
    window.onpageshow = function() {
        new JsDatePick({
            useMode: 2,
            target: "inputFieldto",
            dateFormat: "%Y-%m-%d"
        });

        new JsDatePick({
            useMode: 2,
            target: "inputFieldfrom",
            dateFormat: "%Y-%m-%d"
        });
    };
</script>
<div class="top-paneltab">Violations History</div>
<div class=" divcc" >

</div> 
<table align="center">
    <tr>
        <td>
            <form action=" ?tab=violations-history&option=show_dates" method="post"> 
                <div class="divt22">
                    <div style="padding-top:18px;"> From </div>
                </div>
                <div class="divt22">
                    <input type="text" class="search2" onclick="<?php $flagfrom = 1; ?>" size="12" name="from" id="inputFieldfrom" value="<?php echo $from; ?> " style=" background: white url(images/cal2.png) right no-repeat; padding-right: 10px;"/> 
                </div>
                <div class="divt22"> <div class="divtsp"></div> </div>
                <div class="divt22">
                    <div style="padding-top:18px;"> To </div>
                </div>
                <div class="divt22">
                    <input type="text" class="search2" onclick="<?php $flagto = 1; ?>" size="12" name="to" id="inputFieldto" value="<?php echo $to; ?> " style=" background: white url(images/cal2.png) right no-repeat; padding-right: 10px;"/>
                </div>
                <div class="divt22">  <div class="divtsp"></div></div>
                <div class="divt22">
                    <input type="submit" class="btn-search" name="submit" value="show" />
                </div>
            </form>
        </td>
    </tr>
</table>
<div class="divtsp"></div>
<div class="divtsp"></div>

<table class="table1" >
    <tr>
        <td>
            <div class="divt1">
                <input class="history_violation_search search" placeholder="Enter SKU..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action'] == "search" && isset($_GET['tab']) && $_GET['tab'] == 'violations-history') echo $_GET['value']; ?>" id="textBoxSearch"    /> 
            </div>
            <div class="divt22 search-btn-container">
                <button href="javascript:void(0);" class="btn-search"  onclick="search('.history_violation_search', 'sku', 'search');">Search</button>
            </div>
            <div class="divt22">
                <button href="javascript:void(0);" class="btn-search"  onclick="show_all();" >Show all</button>
            </div>
        </td>


        <td> 
            <div class="divt22">
                <select  id="exporth" name="export_to" class="dropdown" >

                    <option value="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
        </td>
        <td>
            <div class="divt22">
                <button href="" id="1" class="btn-search" onclick="exporttoh();">Export</button>
            </div>
        </td>


        <td>
            <div class="results-per-page-block" >
                <select name="recent-limit" class="results-per-page dropdown"  >

                    <option <?php echo ($limit == 15) ? "selected" : ""; ?> value="15">15</option>
                    <option  <?php echo ($limit == 25) ? "selected" : ""; ?> value="25">25</option>
                    <option  <?php echo ($limit == 50) ? "selected" : ""; ?>  value="50">50</option>
                    <option  <?php echo ($limit == 75) ? "selected" : ""; ?> value="75">75</option>
                    <option  <?php echo ($limit == 100) ? "selected" : ""; ?>  value="100">100</option>
                </select>
            </div>
        </td>

    </tr>
</table>
<div class="cleaner" style="padding-top: 15px; ">

</div>
<br/>

<table class="GrayBlack" align="center">
    <tbody id="data">
        <tr> 
            <td>
                SKU

                <a  onclick="sort_grid('sku', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                    <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "sku" ? $direction : "asc" ); ?>_1.png" />
                </a>
            </td>	
            <td>
                Seller

                <a  onclick="sort_grid('wname', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                    <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "wname" ? $direction : "asc" ); ?>_1.png" />
                </a>
            </td>	
            <td>
                Vendor price

                <a  onclick="sort_grid('vendor_price', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                    <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "vendor_price" ? $direction : "asc" ); ?>_1.png" />
                </a>
            </td>
            <td>
                MAP price
                <a  onclick="sort_grid('map_price', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                    <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "map_price" ? $direction : "asc" ); ?>_1.png" />
                </a>

            </td>
            <td>
                Violation amt

                <a  onclick="sort_grid('violation_amount', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                    <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "violation_amount" ? $direction : "asc" ); ?>_1.png" />
                </a>
            </td>
            <td>Date

                <a  onclick="sort_grid('date_executed', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                    <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "date_executed" ? $direction : "asc" ); ?>_1.png" />
                </a>
            </td>
            <td>
                Link
            </td>
        </tr>




        <?php
        foreach ($violators_array as $violator) {

            $cell_id = "vio";
            if ($violator->violation_amount >= 5 && $violator->violation_amount < 10)
                $cell_id = "vioO";
            else if ($violator->violation_amount >= 10)
                $cell_id = "vioR";
            ?>
            <tr>
                <td ><a href="index.php?tab=violation-by-product&action=search&flag=1&field=sku&value=<?php echo $violator->sku; ?>"><?php echo $violator->sku; ?></a></td>

                <td ><a href="index.php?&tab=violation-by-seller&action=search&flag=1&field=name&value=<?php echo $violator->wname; ?>&website_id=<?php echo $violator->website_id; ?>"><?php echo $violator->wname; ?></a></td>
                <td><?php echo toMoney($violator->vendor_price); ?></td>
                <td><?php echo toMoney($violator->map_price); ?></td>
                <td id="<?php echo $cell_id; ?>"><?php echo toMoney($violator->violation_amount); ?></td>
                <td><?php echo $violator->date_executed; ?></td>
                <td><a href="<?php echo $product->website_product_url; ?>" target="_blank">View</a></td>
            </tr>				
        <?php } ?>

    </tbody></table> 


<?php
if (count($violators_array) == 0) {
    ?><table class="GrayBlack" align="center">
        <tr align="center"><td width="500"> No Records Found  </td> </tr></table>
<?php }
?>

<div align="left" style="display:block; ">
    <?php echo $pagination_html; ?>
</div>		
<div class="divtsp"></div>
<div class=" divcc" >
</div> 
<div  class="chartt">
    <table>
        <tr>
            <td>
                <?php include_once 'charts/a5.php'; ?>
            </td>
            <td>
                <?php include_once 'charts/a6.php'; ?>
            </td>
        </tr>

    </table>
</div>

