<script type="text/javascript">
    window.onpageshow = function() {
        new JsDatePick({
            useMode: 2,
            target: "inputFieldto",
            dateFormat: "%Y-%m-%d"

        });

        new JsDatePick({
            useMode: 2,
            target: "inputFieldfrom",
            dateFormat: "%Y-%m-%d"
        });
    };
</script>
<div style=" align:center">
                     <div class="divt2222">
                            <img src="./images/red.png" value="red"/>  </div> <div class="divt2223">Violation amount > 10 </div> 
            
                        <div class="divt2222">
                            <img src="./images/brown.png" /></div> <div class="divt2223"> Violation amount < 10 and > 5 </div> 
            
                        <div class="divt2222">
                            <img src="./images/blue.png" /></div> <div class="divt2223">Violation amount < 5 </div> 

          
</div>
<div style=" width: 100%; padding-top: 50px;" >
    
    <div style="clear:  left; float: left; width:60%; "> 
        <form action="<?php echo $urls ?>" method="post"> 
            <div class="divt2222">
                <div style="padding-top:15px;"> From </div>
            </div>
            <div class="divt2222">
                <input type="text" class="search2" onclick="<?php $flagfrom = 1; ?>" size="12" name="from" id="inputFieldfrom" value="<?php echo $from; ?> " style=" background: white url(images/cal2.png) right no-repeat; padding-right: 10px;"/> 
            </div>
            <div class="divt2222"> <div class="divtsp"></div> </div>
            <div class="divt2222">
                <div style="padding-top:15px;"> To </div>
            </div>
            <div class="divt2222">
                <input type="text" class="search2" onclick="<?php $flagto = 1; ?>" size="12" name="to" id="inputFieldto" value="<?php echo $to; ?> " style=" background: white url(images/cal2.png) right no-repeat; padding-right: 10px;"/>
            </div>
            <div class="divt2222">  <div class="divtsp"></div></div>
            <div class="divt2222">
                <input type="submit" class="btn-search" name="submit" value="Search" />
            </div>
        </form>
        <div class="divt2222">
            <form name="showall" action ="index.php?tab=violations-history" method="post">
                <button type="submit" name="showall" value="true" href="javascript:void(0);" class="btn-search" style="width: 120px;" onclick="show_all();" >Reset Search</button>

              
            </form>
        </div>
       
        <div style="align: right; float: right ">
            <a target="_blank" href="./export/export_history_csv.php" id="exporth"> <img src="./images/CSV.png" style="height:40px; width: 40px; box-shadow: 4px 4px 5px #888888;"  /></a>
            <a target="_blank" href="./export/export_history_pdf.php" id="exporth"> <img src="./images/PDF.png" style="height:40px; width: 40px; box-shadow: 4px 4px 5px #888888 "  /></a>
            <a target="_blank" href="./export/export_history_xls.php" id="exporth"> <img src="./images/XLS.png" style="height:40px; width: 40px; box-shadow: 4px 4px 5px #888888"  /></a>
        </div>
       <div class="results-per-page-block"  style="align: right; float: right ;padding-top: 10px; padding-right: 10px;">
           <div class="divt2222">
                <div style="padding:5px; padding-top: 6px;">Show</div>
            </div>
           <select name="recent-limit" class="results-per-page dropdown"  >

                <option <?php echo ($limit == 15) ? "selected" : ""; ?> value="15">15</option>
                <option  <?php echo ($limit == 25) ? "selected" : ""; ?> value="25">25</option>
                <option  <?php echo ($limit == 50) ? "selected" : ""; ?>  value="50">50</option>
                <option  <?php echo ($limit == 75) ? "selected" : ""; ?> value="75">75</option>
                <option  <?php echo ($limit == 100) ? "selected" : ""; ?>  value="100">100</option>
                <option <?php echo ($limit == 200) ? "selected" : ""; ?> value="200">200</option>
                <option  <?php echo ($limit == 500) ? "selected" : ""; ?> value="500">500</option>
                <option  <?php echo ($limit == 1000) ? "selected" : ""; ?>  value="1000">1000</option>

            </select>
            <div class="divt2222">
                <div style="padding:5px; padding-top: 6px;"> Records</div>
            </div>
        </div>
        <div>
            

        </div>

        <div class="divtsp"></div>
        <div class="divtsp"></div>


       <div class="cleaner" style="padding-top: 15px; ">

        </div>



        <table class="GrayBlack"  align="left" style="width: 100%;">

            
   <tbody>

                <tr > 
                    <td>

                        <div id="checkboxlisth">
                            <input type="checkbox" id="selectallh" value="1"/>
                        </div>
                        <div id="selectallrechcontainer" style="padding-top: 5px;">
                            <a id="selectallrech" href="#" class="selectallrech" >Select all</a>
                        </div>
                    </td>
                    <td>



                        <a  onclick="sort_grid('sku', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                            SKU 
                        </a>

                        <?php if ($order_field == "sku") { ?>
                            <a  onclick="sort_grid('sku', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                                <img  style="float:right;" src="images/arrow_<?php echo ( $order_field == "sku" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        <?php } ?>

                        <form name="productSearch" action="JavaScript:searchPro();" method="get">
                            <input type="text" class="search" name="product" id="txtproduct" placeholder="Search SKU..." value="<?php if(isset($_GET['product'])){ echo $_GET['product'];} elseif(isset($_GET['sku'])){ echo $_GET['sku']; }?>" />
                        </form>


                    </td>	
                    <td>


                        <a  onclick="sort_grid('vendor', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                            Dealer
                        </a>
<?php if ($order_field == "vendor") { ?>
                            <a  onclick="sort_grid('vendor', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                                <img  style="float:right;"  src="images/arrow_<?php echo ( $order_field == "vendor" ? $direction : "asc" ); ?>_1.png" />
                            </a>
<?php } ?>
                        <form name="dealerSearch" action ="JavaScript:searchVen();" method="get">
                            <input type="text" class="search" name="dealer" id="txtvendor" placeholder="Search Vendor..." value="<?php if(isset($_GET['dealer'])) echo $_GET['dealer']; elseif(isset($_GET['wname'])){ echo $_GET['wname']; }?>"/>
                        </form>

                    </td>	
                    <td>


                        <a  onclick="sort_grid('vendor_price', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                            Dealer price  
                        </a>
<?php if ($order_field == "vendor_price") { ?>
                            <a  onclick="sort_grid('vendor_price', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                                <img  style="float:right;"  src="images/arrow_<?php echo ( $order_field == "vendor_price" ? $direction : "asc" ); ?>_1.png" />         
                            </a>
<?php } ?>
                    </td>
                    <td>

                        <a  onclick="sort_grid('map_price', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                            MAP price
                        </a>
<?php if ($order_field == "map_price") { ?>
                            <a  onclick="sort_grid('map_price', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                                <img  style="float:right;"  src="images/arrow_<?php echo ( $order_field == "map_price" ? $direction : "asc" ); ?>_1.png" />
                            </a>
<?php } ?>

                    </td>
                    <td>


                        <a  onclick="sort_grid('violation_amount', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                            Violation amt 
                        </a>
<?php if ($order_field == "violation_amount") { ?>
                            <a  onclick="sort_grid('violation_amount', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                                <img  style="float:right;"  src="images/arrow_<?php echo ( $order_field == "violation_amount" ? $direction : "asc" ); ?>_1.png" />
                            </a>
<?php } ?>
                    </td>
                    <td>

                        <a  onclick="sort_grid('date_executed', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                            Date
                        </a>
<?php if ($order_field == "date_executed") { ?>
                            <a  onclick="sort_grid('date_executed', '<?php echo ($direction == "asc" ? "desc" : "asc") ?>', 'history');" href="javascript:void(0);">
                                <img  style="float:right;" src="images/arrow_<?php echo ( $order_field == "date_executed" ? $direction : "asc" ); ?>_1.png" />
                            </a>
<?php } ?>
                    </td>
                    <td> <a>Link</a>

                    </td>
                </tr>
           


           
         

                <?php
                foreach ($violators_array as $violator) {


                 
                    $product_link = "?tab=violations-history&product_id=" . $violator->product_id . "&sku=" . $violator->sku;
                    if(isset($_GET['option']) and $_GET['option']=="show_dates")
                          $product_link.="&option=show_dates";                
                    


                   
                    $vendor_link = "?tab=violations-history&website_id=" . $violator->website_id . "&wname=" . $violator->vendor;
                     if(isset($_GET['option']) and $_GET['option']=="show_dates")
                          $vendor_link.="&option=show_dates";  






                    $cell_id = "vio";
                    if ($violator->violation_amount >= 5 && $violator->violation_amount < 10)
                        $cell_id = "vioO";
                    else if ($violator->violation_amount >= 10)
                        $cell_id = "vioR";
                    ?>
                    <tr>
                        <td>
    <?php $checkidh = $violator->id; ?>
                            <input type="checkbox"  class="caseh" id="caseh" name="caseh" value="<?php echo $checkidh; ?>"    /> 
                        </td>

                                         
                        <td><a href="<?php echo $product_link; ?>"><?php echo $violator->sku; ?></a></td>
                        <td><a href="<?php echo $vendor_link; ?>"><?php echo $violator->vendor; ?></a></td>
                        <td><?php echo toMoney($violator->vendor_price); ?></td>
                        <td><?php echo toMoney($violator->map_price); ?></td>
                        <td id="<?php echo $cell_id; ?>"><?php echo toMoney($violator->violation_amount); ?></td>
                        <td><?php echo $violator->date_executed; ?></td>
                        <td><a href="<?php echo $violator->website_product_url; ?>" target="_blank">View</a></td>
                    </tr>				
<?php } ?>

            </tbody></table>  <?php
            if (count($violators_array) == 0) {
                ?><table class="GrayBlack" align="left;">
                <tr align="center"><td width="900" hight="30"> No Records Found  </td> </tr></table>
        <?php }
        ?>   
        <div class="cleaner" style="padding-top: 5px; ">

        </div>
        <div  align="left" style="padding-bottom: 10px;" >

<?php echo $pagination_html; ?>
        </div> 


    </div>
    <div style="height: 100%;float: right; width: 39%;" >

       
        <?php
        if (isset($_REQUEST['website_id'])) {
            ?>
            <table>
                <tr><td>
                        <div>
    <?php include_once 'charts/a4.php'; ?>
                        </div>

                    </td>
                </tr>
                <tr><td>
                        <div style="float: left; padding-top:  50px; padding-left: 6px;"> 
    <?php include_once 'charts/a6.php'; ?>
                        </div>

                    </td>
                </tr>

            </table>
            <?php
        } elseif (isset($_REQUEST['product_id'])) {
            ?>
            <table>
                <tr><td>
                        <div>
    <?php include_once 'charts/a3.php'; ?>
                        </div>

                    </td>
                </tr>
                <tr><td>

                        <div style="float: left; padding-top:  50px; padding-left: 6px;"> 
    <?php include_once 'charts/a5.php'; ?>
                        </div>
                    </td>
                </tr>
            </table>
            <?php
        } else {
            ?>

            <table>
                <tr><td>

                        <div style="clear:left; padding-top: 50px;padding-left: 6px; "> 
    <?php include_once 'charts/a5.php'; ?>
                        </div>

                    </td>
                </tr>
                <tr><td>
                        <div style="float: left; padding-top:  50px; padding-left: 6px;"> 
    <?php include_once 'charts/a6.php'; ?>
                        </div>
                    </td>
                </tr>

            </table>
<?php } ?>
    </div>
</div>


