<script type="text/javascript">



    /* Function removes search params to prevent overlay on other tab. Using for limit,pagination*/
    function check_for_search_params() {
        if (queryParameters['tab'] != selected_tab) {
            delete  queryParameters['action'];
            delete queryParameters['field'];
            delete queryParameters['value'];
        }
    }




    /*product_violation_tab.phtml*/
    function exporttop() {
        var mode = $("#exportp").val();
        queryParameters['tab'] = "violation-by-product";
        if (mode)
            open("export/export_product_" + mode + ".php?" + $.param(queryParameters));
    }

    /*Common search function*/
    function search() {
		
		var action="search";
		      
        var value_sku = $('.'+selected_tab+' .search-sku').val();
        var value_dealer = $('.'+selected_tab+' .search-dealer').val();
		var date_from=$('.'+selected_tab+' #inputFieldfrom').val();
     	var date_to=$('.'+selected_tab+' #inputFieldto').val();
     	
        var v_id = queryParameters['website_id'];
        var p_id = queryParameters['product_id'];
        queryParameters = {}; //clear parameters
        queryParameters['tab'] = selected_tab;

		if (date_from) {
			 queryParameters['from'] = date_from;
		}
		if (date_to) {
			 queryParameters['to'] = date_to;
		}
        
		if (value_sku) {
			 queryParameters['sku'] = value_sku;
		}

		if (value_dealer) {
			 queryParameters['dealer'] = value_dealer;
		}
		
        if (value_sku || value_dealer) {
            queryParameters['action'] = action;
        }
        if (v_id)
            queryParameters['website_id'] = v_id;
        if (p_id)
            queryParameters['product_id'] = p_id;
        
        location.search = '?' + $.param(queryParameters);
    }
    /*Common search function*/





    /*Show all common method*/
    function show_all() {
      
     location.search='?tab='+selected_tab ;  	        
    }
    /*Show all common method*/

    function show_all2() {
        if (queryParameters['searchvendor']) {
         
                delete  queryParameters['searchvendor'];
                delete  queryParameters['limit2'];
               
            }
            if (queryParameters['searchproduct']) {
         
                delete  queryParameters['searchproduct'];
                delete  queryParameters['limit2'];
               
            }
       
        if (queryParameters['page2']) {
            delete queryParameters['page2'];
        }
        queryParameters['tab'] = selected_tab;
        location.search = '?' + $.param(queryParameters);
 }

 

    /*Limits functions*/
    $(document).ready(function() {
        $('.results-per-page').each(function() {
            $(this).change(function() {
                check_for_search_params();
                var limit = $(this).val();
                queryParameters['tab'] = selected_tab;
                queryParameters['limit'] = limit;
                location.search = '?' + $.param(queryParameters);
            });
        });

        $('.results-per-page2').each(function() {
            $(this).change(function() {
                check_for_search_params();
                var limit = $(this).val();
                queryParameters['tab'] = selected_tab;
                queryParameters['limit2'] = limit;
                location.search = '?' + $.param(queryParameters);
            });
        });

        /*Binding enter search*/
        $(".recent_violation_search, .product-violation-search, .vendor-violation-search, .history_violation_search").keypress(function(e) {
            if (e.which == 13) {
                $(this).parent().parent().children('.search-btn-container').children('button').click();
                $(this).parent().parent().children('.search-btn-container1').children('button').click();
            }
        });
        /*Binding enter search*/

        /*Binding enter search 2nd grids*/
        $(".product-violation-search2, .vendor-violation-search2, .history-search2").keypress(function(e) {
            if (e.which == 13) {
                $(this).parent().parent().children('.search-btn-container').children('button').click();
            }
        });
	
        /*Binding enter search 2nd grids*/

    });
    /*Limits functions*/
    /*Pagination function*/
    function switch_page(page_num, param_name) {
        check_for_search_params(); // to prevent search params in query
        queryParameters['tab'] = selected_tab;
        queryParameters[param_name] = page_num;
        location.search = '?' + $.param(queryParameters);
    }
    /*Pagination function*/

    /*Global sorting links*/
    function sort_grid(field, direction, grid) {
        check_for_search_params(); // to prevent search params from different tab in query
        queryParameters['tab'] = selected_tab;
        queryParameters['grid'] = grid;
        queryParameters['dir'] = direction;
        queryParameters['sort'] = field;
        location.search = '?' + $.param(queryParameters);
    }
    /*Global sorting links*/
    /*product_violation_tab.phtml*/

    /*product_violation_detail.phtml*/
    function exporttop2() {
        var mode = $("#exportp2").val();
        var url_options = window.location.search.substring(1);

        if (url_options.length)
            url_options = '?' + url_options;


        if (mode)
            open("export/export_product2_" + mode + ".php" + url_options);
    }
    /*product_violation_detail.phtml*/


    /*vendor_violation_tab*/
    function exporttov() {
        var mode = $("#exportv").val();
        var url_options = window.location.search.substring(1);

        if (url_options.length)
            url_options = '?' + url_options;

        if (mode)
            open("export/export_vendor_" + mode + ".php" + url_options);
    }
    /*vendor_violation_tab*/

    /*vendor_violation_detail*/
    function exporttov2() {
        var mode = $("#exportv2").val();
        var url_options = window.location.search.substring(1);

        if (url_options.length)
            url_options = '?' + url_options;

        if (mode)
            open("export/export_vendor2_" + mode + ".php" + url_options);
    }
    /*vendor_violation_detail*/




    /*history*/
    function exporttoh()
    {
        var mode = $("#exporth").val();
        var url_options = window.location.search.substring(1);

        if (url_options.length)
            url_options = '?' + url_options;

        if (mode)
            open("export/export_history_" + mode + ".php?" + $.param(queryParameters));
       

    }

    function checkTextField(field) {
        if (field.value == '') {
            var $searchsku = 1;
        }
    }
    /*history*/


    /* Select All Checkboxes common*/
    function select_all_checkboxes(obj){        

    var checked=1;
    if ($(obj).prop("checked")) {
    	checked=0; 
    }

	 if ($(obj).parent().parent().find("input[type=hidden]").val()==1) {  
		$(obj).parent().parent().find("input[type=hidden]").val(0);
		$(obj).parent().parent().find("input[type=hidden]").parent().children("a").html("Select All");
	} 
		
   	 $(obj).parent().parent().parent().parent().parent().find("input[type=checkbox]").not('#'+$(obj).attr("id")).each(function() {  //up to GrayBlack   	   	  
   	   	  if (checked) {
   	   	   	$(this).removeProp("checked")
   	   	  } else {
   	   	   	$(this).prop("checked", "checked");
   	   	  }
   	 });      
    }      
   /* Select All  Checkboxes common*/
   /* Select All  Button common*/
    function   select_all(obj){     
         
      if ( $(obj).parent().children("input").val()==1) {
      	 if ($(obj).parent().parent().find("input[type=checkbox]").prop("checked"))
    		 $(obj).parent().parent().find("input[type=checkbox]").click();
   		 $(obj).parent().children("input").val(0);
    	 $(obj).html("Select All");
      } else {
    	  if (!$(obj).parent().parent().find("input[type=checkbox]").prop("checked"))
    		  $(obj).parent().parent().find("input[type=checkbox]").click();
    	  $(obj).parent().children("input").val(1);
    	  $(obj).html("Unselect All");
      }
     	 
    }
    /* Select All  Button common*/
    /*New export function*/
   function export2file(tab,type,grid_class, order_field,order_direction, DateFromId, DateToId) {
	var all_from_page=0;
	var selected_all=0;
		 
	selected_all=parseInt($("."+grid_class+" .select_all_value").val());
	 if (selected_all) {		
		 queryParameters['row_ids']="all";
	 }else if (!selected_all && $("."+grid_class+" .select_all_value").parent().parent().find("input[type=checkbox]").prop("checked")) {
		all_from_page=1;	
		queryParameters['limit']=$(".limit-"+grid_class).val();	
		queryParameters['row_ids']="limit"; 		 
	}   else if (!selected_all && !all_from_page) {
		var ids_array=[];
		$("."+grid_class).find("input[type=checkbox]:checked").not('#'+$("."+grid_class+" .select_all_value").parent().parent().find("input[type=checkbox]").attr("id")).each(function() {
			ids_array.push($(this).val());
		});		 
		queryParameters['row_ids']=ids_array.join(",");
		if (ids_array.length==0) {
			queryParameters['limit']=$(".limit-"+grid_class).val();	
			queryParameters['row_ids']="limit"; 
		}
	} 

	if (DateFromId.length && DateToId.length) {
		queryParameters['from']=jQuery(DateFromId).val();
		queryParameters['to']=jQuery(DateToId).val();
	}
	 
	queryParameters['order_field']=order_field;
	queryParameters['order_direction']=order_direction;
	   open("export/export_"+tab+"_" + type + ".php?" + $.param(queryParameters));
   }
   /*New export function*/
   	
//checkbox history tab
    function getValueUsingClassh() {
        /* declare an checkbox array */
        var chkArrayh = [];
        var chkallh = [];
        /* look for all checkboes that have a class 'chk' attached to it and check if it was checked */
        $(".caseh:checked").each(function() {
            chkArrayh.push($(this).val());
        });

        /* we join the array separated by the comma */
        var selectedh;
        selectedh = chkArrayh.join(',') + ",";
        selectedh = selectedh.slice(0, -1);
        if (selectedh.length > 1) {
            // alert("You have selected " + selectedh);
        } else {
            // alert("Selected none");  
            selectedh = 0;
        }

        //////////

        /* look for all checkboes that have a parent id called 'checkboxlist' attached to it and check if it was checked */
        $("#checkboxlisth input:checked").each(function() {
            chkallh.push($(this).val());
            // var selectedallh= chkallh;
        });
//         alert(selectedh);
         $.post('./export/export_history_csv.php', 'listh=' + selectedh, function(response) {
//                     alert(response);
                 });
                   $.post('./export/export_history_pdf.php', 'listh=' + selectedh, function(response) {
//                     alert(response);
                 });
                   $.post('./export/export_history_xls.php', 'listh=' + selectedh, function(response) {
//                     alert(response);
                 });

         



    }
 

/////History end
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//check product details

//check all product details
    $(function() {

        // add multiple select / deselect functionality
        $("#selectallp").click(function() {
            $('.casep').prop('checked', this.checked);
        });

        // if all checkbox are selected, check the selectall checkbox
        // and viceversa
        $(".casep").click(function() {

            if ($(".casep").length == $(".casep:checked").length) {
                $("#selectallp").prop("checked", "checked");
            } else {
                $("#selectallp").removeProp("checked");
            }

        });

    });

 
    $(document).ready(function() {
        $("#buttonClassp,#buttonClassp,#buttonClassp,#checkboxlistp,#casep,#exportp").click(function() {
            getValueUsingClassp();
        });
    });
//checkbox product details
    function getValueUsingClassp() {
        /* declare an checkbox array */
        var chkArrayp = [];
        var chkallp = [];
        /* look for all checkboes that have a class 'chk' attached to it and check if it was checked */
        $(".casep:checked").each(function() {
            chkArrayp.push($(this).val());
        });

        /* we join the array separated by the comma */
        var selectedp;
        selectedp = chkArrayp.join(',') + ",";
        selectedp = selectedp.slice(0, -1);
        if (selectedp.length > 1) {
            // alert("You have selected " + selectedh);
        } else {
            // alert("Selected none");  
            selectedp = 0;
        }

        //////////

        /* look for all checkboes that have a parent id called 'checkboxlist' attached to it and check if it was checked */
        $("#checkboxlistp input:checked").each(function() {
            chkallp.push($(this).val());
        });

//alert(selectedp);

        $.post('./export/export_product2_csv.php', 'listp=' + selectedp, function(response) {
//                     alert(response);
                });
                $.post('./export/export_product2_pdf.php', 'listp=' + selectedp, function(response) {
//                    alert(response);
                });
                $.post('./export/export_product2_xls.php', 'listp=' + selectedp, function(response) {
//                    alert(response);
                });



    }

    $('.selectallrecP').click(function() {
        window.location.href = 'index.php?tab=violations-history&' + $.param(queryParameters) + '&selectallproduct=1';
        delete queryParameters['selectallproduct'];
        delete queryParameters['listp'];

    });


///////product details end
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


//check vendor details

//check all vendor details
    $(function() {

        // add multiple select / deselect functionality
        $("#selectallv").click(function() {
            $('.casev').prop('checked', this.checked);
        });

        // if all checkbox are selected, check the selectall checkbox
        // and viceversa
        $(".casev").click(function() {

            if ($(".casev").length == $(".casev:checked").length) {
                $("#selectallv").prop("checked", "checked");
            } else {
                $("#selectallv").removeProp("checked");
            }

        });

    });





    $(document).ready(function() {
        $("#buttonClassv,#buttonClasshv,#buttonClasshv,#checkboxlistv,#casev,#exportv").click(function() {
         //   getValueUsingClassv();
        });
    });
//checkbox vendor details
    function getValueUsingClassv() {
        /* declare an checkbox array */
        var chkArrayv = [];
        var chkallv = [];
        /* look for all checkboes that have a class 'chk' attached to it and check if it was checked */
        $(".casev:checked").each(function() {
            chkArrayv.push($(this).val());
        });

        /* we join the array separated by the comma */
        var selectedv;
        selectedv = chkArrayv.join(',') + ",";
        selectedv = selectedv.slice(0, -1);
        if (selectedv.length > 1) {
            // alert("You have selected " + selectedh);
        } else {
            // alert("Selected none");  
            selectedv = 0;
        }

        //////////

        /* look for all checkboes that have a parent id called 'checkboxlist' attached to it and check if it was checked */
        $("#checkboxlistv input:checked").each(function() {
            chkallv.push($(this).val());
        });




                $.post('./export/export_vendor2_csv.php', 'listv=' + selectedv, function(response) {
//                     alert(response);
                });
                $.post('./export/export_vendor2_pdf.php', 'listv=' + selectedv, function(response) {
//                    alert(response);
                });
                $.post('./export/export_vendor2_xls.php', 'listv=' + selectedv, function(response) {
//                    alert(response);
                });


    }

    $('.selectallrecV').click(function() {
        window.location.href = 'index.php?tab=violations-history&' + $.param(queryParameters) + '&selectallvendor=1';
        delete queryParameters['selectallvendor'];
        delete queryParameters['listv'];

    });
    delete queryParameters['selectallvendor'];
    delete queryParameters['listv'];

    delete queryParameters['selectallproduct'];
    delete queryParameters['listp'];

    delete queryParameters['selectallhistory'];
    delete queryParameters['listh'];



///// vendor details end
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////


function searchPro(){
var pro = document.getElementById("txtproduct").value;
 window.location ="index.php?tab=violations-history&product="+pro+"&"+ $.param(queryParameters);
    

}
function searchVen(){
var ven = document.getElementById("txtvendor").value;
 window.location ="index.php?tab=violations-history&dealer="+ven+"&"+ $.param(queryParameters);
    

}
function searchProDetail(){
var venDetail = document.getElementById("txtproductDetail").value;
 window.location ="index.php?tab=violations-history&"+ $.param(queryParameters)+"&searchvendor="+venDetail;
 }
 function searchVenDetail(){
var proDetail = document.getElementById("txtvendorDetail").value;
 window.location ="index.php?tab=violations-history&"+ $.param(queryParameters)+"&searchproduct="+proDetail;
 }


</script>
