<script type="text/javascript">
/*recent_tab.phtml*/
 function exportr(){
	var mode = $("#exportr").val();
	if (mode)
		open("export/export_recent_" + mode + ".php?" + $.param(queryParameters));
}
 
		/* Function removes search params to prevent overlay on other tab. Using for limit,pagination*/
	function check_for_search_params(){
		if (queryParameters['tab']!=selected_tab) {			 
			delete  queryParameters['action'];
			delete queryParameters['field'];
			delete queryParameters['value'];
		}
	}
        
  
/*recent_tab.phtml*/

/*product_violation_tab.phtml*/
         function exporttop(){
     		var mode = $("#exportp").val();	 
     		queryParameters['tab'] = "violation-by-product";
     		if (mode)
     			open("export/export_product_" + mode + ".php?" + $.param(queryParameters));
     	}
     		
     	/*Common search function*/
     	  function search(name, search_field, action) {
     		
     	        
     	        var field = search_field;
     		  var value = $(name).val();
     	          
//     	          if((queryParameters['website_id'])==null)
//     	              {
//     	                  var v_id=<?php //$website_id  ?>;
//     	              }
//     	              else
//     	                  {
//     	                       var v_id=queryParameters['website_id'];
//     	                  }
     	          //if(queryParameters['product_id']=='undefined')
     	            //  {
     	              //    var v_id=<?php //$product_id  ?>;
     	             // }
     	          
     	          
     		  var v_id=queryParameters['website_id'];
     		  var p_id=queryParameters['product_id'];
     		  queryParameters={}; //clear parameters
     		  queryParameters['tab'] = selected_tab;
     		  
     		  if (value.length) {
     		     	queryParameters['action'] = action;
     		     	queryParameters['field'] = field;
     		     	queryParameters['value'] =  value;
     		  }
     		  if (v_id) 
     			  queryParameters['website_id']=v_id;
     		  if (p_id)
     			  queryParameters['product_id']=p_id;
     		     	     location.search='?'+$.param(queryParameters);  
     	            
     	            
     	  }
     	 /*Common search function*/
     	 

     	 
     	 
     	 /*Show all common method*/
     	 function show_all() {		  
     		location.search='?tab='+selected_tab ;
     	      //  window.open(search_field, "_self");
     	        
     	 }
     	 /*Show all common method*/
     	 
     	 function show_all2() {           
     		 if(queryParameters['action']) {
     	        if (queryParameters['action']=='search2') {
     	                delete  queryParameters['action'];
     	                delete queryParameters['field'];
     	                delete queryParameters['value'];
     	        }
     		 }
     	        if (queryParameters['page2']) {
     	                delete queryParameters['page2'];
     	        }
     	        queryParameters['tab'] = selected_tab;
     	         location.search='?'+$.param(queryParameters);
     		 
     	 }
     	 
     	 
     	 
     	  /*Limits functions*/
     	 $(document).ready(function() {
     		 $('.results-per-page').each(function() {	  
     			  $(this).change(function() {  
     				   check_for_search_params(); 
     					var limit=$(this).val();    			 
     			    	queryParameters['tab'] = selected_tab;
     					queryParameters['limit'] = limit;	 
     			    	location.search='?'+$.param(queryParameters);
     				}); 
     	 	});

     		$('.results-per-page2').each(function() {	  
     				  $(this).change(function() {  
     					  check_for_search_params(); 
     						var limit=$(this).val();    			 
     					    queryParameters['tab'] = selected_tab;
     						queryParameters['limit2'] = limit;	 
     					    location.search='?'+$.param(queryParameters);
     					}); 
     			});	 	
     		
     		/*Binding enter search*/
     		$(".recent_violation_search, .product-violation-search, .vendor-violation-search, .history_violation_search").keypress(function(e) {
     		    if(e.which == 13) {
     		        $(this).parent().parent().children('.search-btn-container').children('button').click();
     		    }
     		});	
     		/*Binding enter search*/
     		
     		/*Binding enter search 2nd grids*/
     		$(".product-violation-search2, .vendor-violation-search2, .history-search2").keypress(function(e) {
     		    if(e.which == 13) {
     		        $(this).parent().parent().children('.search-btn-container').children('button').click();
     		    }
     		});
                $(".history-search2").keypress(function(e) {
     		    if(e.which == 13) {
     		        $(this).parent().parent().children('.search-btn-container1').children('button').click();
     		    }
     		});	
     		/*Binding enter search 2nd grids*/
     		
     	 });
     	 /*Limits functions*/
     	 /*Pagination function*/
     	 function switch_page(page_num, param_name){
     		 	check_for_search_params(); // to prevent search params in query
     			queryParameters['tab'] = selected_tab;
     			queryParameters[param_name] = page_num;	 
     			location.search='?'+$.param(queryParameters);
     		}
     	 /*Pagination function*/

     	 /*Global sorting links*/
     	function sort_grid(field,direction, grid){
     		check_for_search_params(); // to prevent search params from different tab in query
     		queryParameters['tab'] = selected_tab;
     		queryParameters['grid'] = grid;
     		queryParameters['dir'] = direction;
     		queryParameters['sort'] = field;
     		location.search='?'+$.param(queryParameters);
     	}
     	 /*Global sorting links*/         
/*product_violation_tab.phtml*/

/*product_violation_detail.phtml*/
        function exporttop2() {
            var mode = $("#exportp2").val();
            var url_options = window.location.search.substring(1);

            if (url_options.length)
                url_options = '?' + url_options;


            if (mode)
                open("export/export_product2_" + mode + ".php" + url_options);
        }
/*product_violation_detail.phtml*/


/*vendor_violation_tab*/
        function exporttov() {
            var mode = $("#exportv").val();
            var url_options = window.location.search.substring(1);

            if (url_options.length)
                url_options = '?' + url_options;

            if (mode)
                open("export/export_vendor_" + mode + ".php" + url_options);
        }
/*vendor_violation_tab*/
        
/*vendor_violation_detail*/   
        function exporttov2() {
            var mode = $("#exportv2").val();
            var url_options = window.location.search.substring(1);

            if (url_options.length)
                url_options = '?' + url_options;

            if (mode)
                open("export/export_vendor2_" + mode + ".php" + url_options);
        }        
/*vendor_violation_detail*/   

/*history*/
        function exporttoh()
        {
            var mode = $("#exporth").val();
            var url_options = window.location.search.substring(1);

            if (url_options.length)
                url_options = '?' + url_options;

            if (mode)
                open("export/export_history_" + mode + ".php?" + $.param(queryParameters));
            //open("export_history_" + mode + ".php" + url_options);

        }        
/*history*/
        
</script>
