<div id="templatemo_header_wrapper">
	<div class="container" style="margin: auto; width: 980px; height: 80px; min-height: 2px; overflow: auto;">
		<div style="float: left; padding-right: 30px">
			<a href="/" target="_blank"><img src="images/Kraus-Logo-HQ.png"
				width="186" height="71" /> </a>
		</div>
		<div class="left-part" style="float: left; width: 200px;">
			<h2>Price Defender</h2>
		</div>
	</div>
</div>

<div id="templatemo_footer_wrapper1">
	<div id="templatemo_footer">
		<div align="center" style="min-height: 30px; overflow: auto;">
		</div>
	</div>
</div>
