<h3 align="center"	>Product Violations</h3>
<table align="center"  width="1000px" >
    <tr>
        <td>
        <td>
            <div style="padding-right: 20px;padding-left:0px; float: left">
  <input  	class="product-violation-search search" placeholder="Search here..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action'] == "searchfirst" && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product') echo $_GET['value']; ?>" id="textBoxSearch"  /> 
            </div>
            <div style="padding-right: 20px;padding-left:20px; float:left;">

                <a href="javascript:void(0);" class="myButton"  onclick="product_violation_search();" >Search</a>
            </div>
        	<div style="padding-right: 20px;padding-left:20px; ">

                <a href="javascript:void(0);" class="myButton"  onclick="product_violation_show_all();" >Show all</a>
            </div>
        </td>
        <td>
            <div style="padding-right: 20px;padding-left:0px; float: left">
                Export To

                <select  id="exportp" name="export_to" style=" widht:100px; height:25px; line-height:20px;margin:0;padding:4;" >
                    <option value="csv" name="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
            <div style="padding-right: 20px;padding-left:0px; ">
                <a href="" id="1" class="myButton" onclick="exporttop();">Export</a>
            </div>
        </td>
    </tr>

</table>
<div class="cleaner" style="padding-top: 15px; ">
</div>
<table align="center">
    <tr>
        <td>
            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td>
                            SKU ID
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&grid=vproduct&dir=<?php echo ($direction=="asc" ? "desc" : "asc")?>&sort=sku&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="sku" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>	

                        <td>
                            MAP
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=map_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="map_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td>
                            Total violations
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=i_count&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="i_count" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>	

                        <td>
                            Max Violation amount
                             <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=maxvio&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="maxvio" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td>
                            Min Violation amount
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=minvio&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="minvio" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                    </tr>

<?php



foreach ($page_violated_products as $product) { 

	$product_link = "?tab=violation-by-product&product_id=" .$product->product_id;
	if (isset($_GET['page']) && $_GET['page']) { //adding pagination for first grid/table
		$product_link.="&page=" . $_GET['page'];
	}
	if (isset($_GET['action']) && $_GET['action'] == "searchfirst") { //added that search  was included
		$product_link.="&action=" . $_GET['action'] . "&field=sku&value=" . $_GET['value'];
	}  

     if(count($product)==0)
{
    ?>
                    <tr><td>No Records Found  </td> </tr>
                    
                    <?php
}

                    else{ 
                        ?>
                    
<tr>
	<td><a href="<?php echo $product_link; ?>"><?php echo $product->sku ;?></a></td>
	<td><?php echo $product->map_price ;?></td>
	<td><?php echo $product->i_count ;?></td>
	<td><?php echo  $product->maxvio ;?></td>
	<td><?php echo  $product->minvio ;?></td>
</tr>
<?php }} ?>


</table>	
</td> </tr>       
</tbody></table> 
<script type="text/javascript">
 function exporttop(){
	var mode = $("#exportp").val();
	var url_options = window.location.search.substring(1);

	if (url_options.length)
		url_options = '?' + url_options;

	if (mode)
		open("export_product_" + mode + ".php" + url_options);
}
  
 function product_violation_search() {
     var field = "sku";
     var value = $(".product-violation-search").val();
     var url_options="";
     if (value.length) {
         url_options += "&action=searchfirst&field=" + field + "&value=" + value;
     }

     var search_link = "index.php?tab=violation-by-product"+url_options;
     window.open(search_link, "_self");
 }
 function product_violation_show_all() {
	  var search_link = "index.php?tab=violation-by-product";
	  window.open(search_link, "_self");
 }
</script>   
