<div class="top-paneltab">Product Violations</div>
<div class=" divcc" ></div> 
<table class="table1" >
    <tr>
              <td>
            <div class="divt1">
  <input  	class="product-violation-search search" placeholder="Enter SKU..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action'] == "search" && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product') echo $_GET['value']; ?>" id="textBoxSearch"  /> 
            </div>
            <div class="divt22 search-btn-container">

                <button href="javascript:void(0);" class="btn-search"  onclick="search('.product-violation-search','sku','search');" >Search</button>
            </div>
        	<div class="divt22">

                    <button href="javascript:void(0);" class="btn-search"  onclick="show_all();" >Show all</button>
            </div>
        </td>
        <td>
            <div class="divt22">
              <select  id="exportp" name="export_to" class="dropdown"   >
                    <option value="csv" name="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
              </td>
        <td>
            <div class="divt22">
                <button href="" id="1" class="btn-search" onclick="exporttop();">Export</button>
            </div>
        </td>
            <td>
            <div class="results-per-page-block"  >
            	<select name="product-limit" class="results-per-page dropdown"  >                    
            		<option <?php  echo  ($limit==15) ? "selected" : "" ; ?> value="15">15</option>
            		<option  <?php echo  ($limit==25) ? "selected" : "" ; ?> value="25">25</option>
            		<option  <?php  echo  ($limit==50) ? "selected" : "" ; ?>  value="50">50</option>
                        <option  <?php echo  ($limit==75) ? "selected" : "" ; ?> value="75">75</option>
            		<option  <?php  echo  ($limit==100) ? "selected" : "" ; ?>  value="100">100</option>
            	</select>
            </div>
    </td>
    </tr>

</table>
<div class="cleaner1" >
</div>

            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td>
                            SKU 
                            <a onclick="sort_grid('sku','<?php echo ($direction=="asc" ? "desc" : "asc")?>','vproduct');" href="javascript:void(0);" >
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="sku" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>	

                        <td>
                            MAP
                            <a  onclick="sort_grid('map_price','<?php echo ($direction=="asc" ? "desc" : "asc")?>','vproduct');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="map_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td>
                            Total violations
                             <a  onclick="sort_grid('i_count','<?php echo ($direction=="asc" ? "desc" : "asc")?>','vproduct');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="i_count" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>	

                        <td>
                            Max Violation amount
                             <a  onclick="sort_grid('maxvio','<?php echo ($direction=="asc" ? "desc" : "asc")?>','vproduct');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="maxvio" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td>
                            Min Violation amount
                            <a  onclick="sort_grid('minvio','<?php echo ($direction=="asc" ? "desc" : "asc")?>','vproduct');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="minvio" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        
                        <td>
                            Link
                        </td>
                    </tr>

<?php



foreach ($page_violated_products as $product) { 

	$product_link = "?tab=violation-by-product&product_id=" .$product->product_id."&sku=".$product->sku;
	if (isset($_GET['page']) && $_GET['page']) { //adding pagination for first grid/table
		$product_link.="&page=" . $_GET['page'];
	}
	if (isset($_GET['action']) && $_GET['action'] == "search") { //added that search  was included
		$product_link.="&action=" . $_GET['action'] . "&field=sku&value=" . $_GET['value'];
	}  

                        ?>
                    
<tr>
	<td><a href="<?php echo $product_link; ?>"><?php echo $product->sku ;?></a></td>
	<td><?php echo toMoney($product->map_price) ;?></td>
	<td><?php echo $product->i_count ;?></td>
	<td><?php echo  toMoney($product->maxvio) ;?></td>
	<td><?php echo  toMoney($product->minvio) ;?></td>
        <td><a href="<?php echo $product->website_product_url; ?>" target="_blank">View</a></td>
        
</tr>
<?php } ?>


     
</tbody></table> 

<?php
        if (count($page_violated_products) == 0) {
            ?><table class="GrayBlack" align="center">
            <tr align="center"><td width="500"> No Records Found  </td> </tr></table>
         <?php
        } ?>


<div align="left" style="display:block; " >
   <?php echo $pagination_html; ?>
</div>	
<div class="cleaner1" >

</div>
<div class="cleaner1" >

</div>
 
