<div class="tab-title"> Sellers Violated  <?php  echo $violators_array3[0]->sku; ?> </div>
<!--<h3 align="center" style="padding-top:20px;"> Sellers Violated  <?php //echo  $namep ?> </h3> -->

<table class="table1" >
    <tr>
        <td >
            <div class="divt1">

<input  class="product-violation-search2 search" placeholder="Search here..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action2']) && $_GET['action2']=="search2" && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product') echo $_GET['value2']; ?>"  id="textBoxSearch" onkeyup="tableSearch.search(event);"   /> 
</div>
            <div class="divt2">
                <a href="javascript:void(0);" class="btn-search"  onclick="product_violation_search2();">Search</a>
            </div>
        </td>
        <td> 
            <div class="divt1">
               

                <select  id="exportp2" name="export_to" class="dropdown" >
                         
                    <option value="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
            <div class="divt2">
                <a href="" id="1" class="btn-search" onclick="exporttop2();">Export</a>
            </div>
    </td>
</tr>
</table>
<!-- table part -->
<div class="cleaner1" >

</div>
<table align="center">
    <tr>
        <td>
            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td >Website
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=vendor&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="vendor" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Vendor price
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=vendor_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="vendor_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Map
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=map_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="map_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Violation
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=violation_amount&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="violation_amount" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                      
                    </tr>
                    <?php

if(count($violators_array)==0)
{  ?>
                    <tr align="center"><td> No Records Found  </td> </tr>
                    
                    <?php
}
                                                       
	foreach ($violators_array as $violator) {
		
		$cell_id="vio";
		if ($violator->violation_amount >= 5 && $violator->violation_amount<10 )
			$cell_id="vioO";
		else if ($violator->violation_amount >= 10 )
			$cell_id="vioR";
?>
<tr>
	
    <td><a href="index.php?tab=violation-by-seller&action=searchfirstv&field=website.id&value=<?php echo $violator->website_id; ?>"><?php echo $violator->vendor; ?></a></td>
	<td><?php echo "$".$violator->vendor_price; ?></td>
	<td><?php echo "$".$violator->map_price; ?></td>
       <!-- <td><?php //echo money_format('$%i',$violator->map_price); ?></td> -->
	<td id="<?php echo $cell_id; ?>"><?php echo "$".$violator->violation_amount; ?></td>
				
</tr>				
<?php } ?>
                  
</tbody></table> 

</td>  
</tr>       
</table> 

<script type="text/javascript">
function product_violation_search2() {
	var field2 = "w.`name`";
	var value2 = $(".product-violation-search2").val();
                     
	var search_url_additional_params = "&product_id=<?php echo $product_id;  ?>";

	//var search_link = "/index.php?action=search2&field=" + field + "&value=" + value +"&tab=violation-by-product"+ search_url_additional_params;
        var search_link = "index.php?tab=violation-by-product"+"&action2=search2&field2=" + field2 + "&value2=" + value2 + search_url_additional_params;
	window.open(search_link, "_self");
		tableSearch.runSearch();
}
                                           
function exporttop2(){
	var mode = $("#exportp2").val();
	var url_options= window.location.search.substring(1);
                                
	if (url_options.length)
		url_options='?'+url_options;
                        		
	if (mode)                                    
		open("export_product2_" + mode + ".php"+url_options);
}
</script>