<div class="top-paneltab">Product Violations</div>
<div class=" divcc" >
                &NonBreakingSpace;
            </div> 
<table align="center"  width="1000px" >
    <tr>
        <td>
        <td>
            <div class="divt1">
  <input  	class="product-violation-search search" placeholder="Enter SKU..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action'] == "search" && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product') echo $_GET['value']; ?>" id="textBoxSearch"  /> 
            </div>
            <div class="divt22">

                <button href="javascript:void(0);" class="btn-search"  onclick="search('.product-violation-search','sku','search');" >Search</button>
            </div>
        	<div class="divt22">

                    <button href="javascript:void(0);" class="btn-search"  onclick="show_all();" >Show all</button>
            </div>
        </td>
        <td>
            <div class="divt22">
              <select  id="exportp" name="export_to" class="dropdown"   >
                    <option value="csv" name="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
            <div class="divt22">
                <button href="" id="1" class="btn-search" onclick="exporttop();">Export</button>
            </div>
        </td>
            <td>
            <div class="results-per-page-block" style="float:left;padding-top:6px;" >
            	<select name="product-limit" class="results-per-page dropdown"  >                    
            		<option <?php  echo  ($limit==15) ? "selected" : "" ; ?> value="15">15</option>
            		<option  <?php echo  ($limit==25) ? "selected" : "" ; ?> value="25">25</option>
            		<option  <?php  echo  ($limit==50) ? "selected" : "" ; ?>  value="50">50</option>
                        <option  <?php echo  ($limit==75) ? "selected" : "" ; ?> value="75">75</option>
            		<option  <?php  echo  ($limit==100) ? "selected" : "" ; ?>  value="100">100</option>
            	</select>
            </div>
    </td>
    </tr>

</table>
<div class="cleaner1" >
</div>

            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td>
                            SKU 
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&grid=vproduct&dir=<?php echo ($direction=="asc" ? "desc" : "asc")?>&sort=sku&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="sku" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>	

                        <td>
                            MAP
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=map_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="map_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td>
                            Total violations
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=i_count&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="i_count" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>	

                        <td>
                            Max Violation amount
                             <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=maxvio&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="maxvio" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td>
                            Min Violation amount
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vproduct&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=minvio&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-product' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="minvio" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        
                        <td>
                            Screenshot
                        </td>
                    </tr>

<?php



foreach ($page_violated_products as $product) { 

	$product_link = "?tab=violation-by-product&product_id=" .$product->product_id."&sku=".$product->sku;
	if (isset($_GET['page']) && $_GET['page']) { //adding pagination for first grid/table
		$product_link.="&page=" . $_GET['page'];
	}
	if (isset($_GET['action']) && $_GET['action'] == "search") { //added that search  was included
		$product_link.="&action=" . $_GET['action'] . "&field=sku&value=" . $_GET['value'];
	}  

                        ?>
                    
<tr>
	<td><a href="<?php echo $product_link; ?>"><?php echo $product->sku ;?></a></td>
	<td><?php echo "$".$product->map_price ;?></td>
	<td><?php echo $product->i_count ;?></td>
	<td><?php echo  "$".$product->maxvio ;?></td>
	<td><?php echo  "$".$product->minvio ;?></td>
        <td><a href="<?php echo $product->website_product_url; ?>" target="_blank">Link</a></td>
        
</tr>
<?php } ?>


     
</tbody></table> 

<?php
        if (count($page_violated_products) == 0) {
            ?><table class="GrayBlack" align="center">
            <tr align="center"><td width="500"> No Records Found  </td> </tr></table>
         <?php
        } ?>


<div align="left" style="display:block; " >
  <?php include ('page2.php'); ?>
</div>	
<div class="cleaner1" >

</div>
<div class="cleaner1" >

</div>
<script type="text/javascript">
 function exporttop(){
	var mode = $("#exportp").val();	 
	queryParameters['tab'] = "violation-by-product";
	if (mode)
		open("export/export_product_" + mode + ".php?" + $.param(queryParameters));
}
	
/*Common search function*/
  function search(name, search_field, action) {
	  var field = search_field;
	  var value = $(name).val();
	  var v_id=queryParameters['website_id'];
	  var p_id=queryParameters['product_id'];
	  queryParameters={}; //clear parameters
	  queryParameters['tab'] = selected_tab;
	  
	  if (value.length) {
	     	queryParameters['action'] = action;
	     	queryParameters['field'] = field;
	     	queryParameters['value'] =  value;
	  }
	  if (v_id) 
		  queryParameters['website_id']=v_id;
	  if (p_id)
		  queryParameters['product_id']=p_id;
	     
	     location.search='?'+$.param(queryParameters);  
  }
 /*Common search function*/
 /*Show all common method*/
 function show_all() {		  
	location.search='?tab='+selected_tab ;
      //  window.open(search_field, "_self");
        
 }
 /*Show all common method*/
  /*Limits functions*/
 $(document).ready(function() {
	 $('.results-per-page').each(function() {	  
		  $(this).change(function() {  
			   check_for_search_params(); 
				var limit=$(this).val();    			 
		    	queryParameters['tab'] = selected_tab;
				queryParameters['limit'] = limit;	 
		    	location.search='?'+$.param(queryParameters);
			}); 
 	});

	$('.results-per-page2').each(function() {	  
			  $(this).change(function() {  
				  check_for_search_params(); 
					var limit=$(this).val();    			 
				    queryParameters['tab'] = selected_tab;
					queryParameters['limit2'] = limit;	 
				    location.search='?'+$.param(queryParameters);
				}); 
		});	 	
 });
 /*Limits functions*/
 /*Pagination function*/
 function switch_page(page_num, param_name){
	 	check_for_search_params(); // to prevent search params in query
		queryParameters['tab'] = selected_tab;
		queryParameters[param_name] = page_num;	 
		 location.search='?'+$.param(queryParameters);
	}
 /*Pagination function*/
</script>   
