<h3 align="center">Violations as of the day ( <?php echo $str; ?>)</h3>
<table class="table1" >
    <tr>
        <td >
            <div class="divt1">

               <input  class="recent_violation_search search" placeholder="Search here..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action']=="search" && isset($_GET['tab']) && $_GET['tab'] == 'recent') echo $_GET['value']; ?>"  id="textBoxSearch"    /> 
</div>
            <div class="divt2">
                <a href="javascript:void(0);" class="myButton"  onclick="recent_violation_search();">Search</a>
            </div>
        </td>
        <td> 
            <div class="divt1" style="float:left;width: 156px;">
                Export To

                <select  id="exportr" name="export_to" class="dropdown"  >
                    <option value="csv" name="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
            <div class="divt2" style="float:left;width: 100px;" >
                <a href="" id="1" class="myButton" onclick="exportr();">Export</a>
            </div>
            <div class="results-per-page" style="float:left;padding-top:6px;">
            	<select name="recent-limit" class="recent-res-per-page"  >
            		<option <?php echo  ($limit==10) ? "selected" : "" ; ?> value="10">10</option>
            		<option  <?php echo  ($limit==15) ? "selected" : "" ; ?> value="15">15</option>
            		<option  <?php echo  ($limit==20) ? "selected" : "" ; ?>  value="20">20</option>
            	</select>
            </div>
    </td>
</tr>
</table>

<div class="cleaner1" >

</div>

<table align="center">
    <tr>
        <td>
            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td >SKU
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=recent&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=sku&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'recent' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="sku" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Seller
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=recent&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=name&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'recent' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="name" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Seller price
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=recent&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=vendor_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'recent' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="vendor_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >MAP
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=recent&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=map_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'recent' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="map_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Violation amount
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=recent&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=violation_amount&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'recent' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="violation_amount" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Link
                        
                        </td>
                    </tr>
<?php       
if(count($violators_array)==0)
{  ?>
                    <tr align="center"><td> No Records Found  </td> </tr>
                    
                    <?php
}
	foreach ($violators_array as $violator) {
		
		$cell_id="vio";
		if ($violator->violation_amount >= 5 )
			$cell_id="vioO";
		else if ($violator->violation_amount >= 10 )
			$cell_id="vioR";
?>
<tr>
    <td ><a href="index.php?tab=violation-by-product&action=searchfirst&flag=1&field=sku&value=<?php echo $violator->sku; ?>"><?php echo $violator->sku; ?></a></td>

        <td ><a href="index.php?&tab=violation-by-seller&action=searchfirst1&field=website_id&value=<?php echo $violator->website_id; ?>&website_id=<?php echo $violator->website_id; ?>"><?php echo $violator->name; ?></td>
    
	
	<td><?php echo $violator->vendor_price; ?></td>
	<td><?php echo $violator->map_price; ?></td>
      	<td id="<?php echo $cell_id; ?>"><?php echo $violator->violation_amount; ?></td>
	<td><a href="<?php echo $violator->website_product_url; ?>" target="_blank">Link</a></td>			
</tr>				
<?php } ?>
                  
</tbody></table> 
</table>
 <div align="left" style="display:block; " >
  <?php include ('page2.php'); ?>
</div> 
 
<div  class="chartt">
    <table>
        <tr>
            <td>
                <?php include_once 'charts/a1.php'; ?>
            </td>
            <td>
                <?php include_once 'charts/a2.php'; ?>
            </td>
        </tr>

    </table>
</div>  
            
            
<script type="text/javascript">

 function exportr(){
	var mode = $("#exportr").val();
	if (mode)
		open("export_recent_" + mode + ".php?" + $.param(queryParameters));
}
  
 function recent_violation_search() {
     var field = "sku";
     var value = $(".recent_violation_search").val();
     var url_options="";
     if (value.length) {
         url_options += "&action=search&field=" + field + "&value=" + value;
     }

     var search_link = "index.php?tab=recent"+url_options;
     window.open(search_link, "_self");
 }
 function product_violation_show_all() {
	  var search_link = "index.php?tab=recent";
	  window.open(search_link, "_self");
 }


$('.recent-res-per-page').change(function() {
	var limit=$(this).val();
	queryParameters['limit'] = limit;
	location.search = $.param(queryParameters);	  
});
 
</script>   