<div class="top-paneltab" align="center">Violations as of the day ( <?php echo $str; ?>)</div>
 <div style="height: 100%; width: 100%;">
    <div style="clear:  left; float: left; width:50%"> 
        
<table class="table1" >
    <tr>
        <td >
            <div class="divt1">

               <input  class="recent_violation_search search" placeholder="Enter SKU..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action']=="search" && isset($_GET['tab']) && $_GET['tab'] == 'recent') echo $_GET['value']; ?>"  id="textBoxSearch"    /> 
</div>
            <div class="divt22 search-btn-container">
                <button href="javascript:void(0);" class="btn-search"   onclick="search('.recent_violation_search','sku','search');">Search</button>
            </div>
             <div class="divt22">
                 <button href="javascript:void(0);" class="btn-search"  onclick="show_all();" >Show all</button>
            </div>
        </td>
        <td>  
            <div class="divt22">
               

   <select title="Export" id="exportr" name="export_to"  class="dropdown"  >
       
      
                    <option value="csv" selected>Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>
     
                </select>
                       </div>
              </td>
        <td>
            <div class="divt22"  >
                <button href="" id="1" class="btn-search" onclick="exportr(); ">Export</button>
            </div>
        </td>
        <td>
            <div class="results-per-page-block"  >
            	<select name="recent-limit" class="results-per-page dropdown"  >                   
            		<option <?php  echo  ($limit==15) ? "selected" : "" ; ?> value="15">15</option>
            		<option  <?php echo  ($limit==25) ? "selected" : "" ; ?> value="25">25</option>
            		<option  <?php  echo  ($limit==50) ? "selected" : "" ; ?>  value="50">50</option>
                    <option  <?php echo  ($limit==75) ? "selected" : "" ; ?> value="75">75</option>
            		<option  <?php  echo  ($limit==100) ? "selected" : "" ; ?>  value="100">100</option>
            	</select>
            </div>
    </td>
</tr>
</table>



<div class="cleaner1" >

</div>
<!--<div style="align:right; width: 700px; padding-left: 324px; ">
 <img src="../images/message.png" /></div>-->

<table class="GrayBlack" align="left" style="width: 700px;">
                <tbody id="data">
                    <tr> 
                        <td >SKU
                           <a  onclick="sort_grid('sku','<?php echo ($direction=="asc" ? "desc" : "asc")?>','recent');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="sku" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Dealers
                                      
                             <a  onclick="sort_grid('name','<?php echo ($direction=="asc" ? "desc" : "asc")?>','recent');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="name" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Dealers price
                       
                             <a  onclick="sort_grid('vendor_price','<?php echo ($direction=="asc" ? "desc" : "asc")?>','recent');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="vendor_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >MAP
                       <a  onclick="sort_grid('map_price','<?php echo ($direction=="asc" ? "desc" : "asc")?>','recent');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="map_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Violation amount
                        
                             <a  onclick="sort_grid('violation_amount','<?php echo ($direction=="asc" ? "desc" : "asc")?>','recent');" href="javascript:void(0);">
                           		<img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field=="violation_amount" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                         <td>
                            Link
                        </td>
                       
                    </tr>
<?php
	foreach ($violators_array as $violator) {
		
		$cell_id="vio";
		if ($violator->violation_amount >= 5 && $violator->violation_amount<10 )
			$cell_id="vioO";
		else if ($violator->violation_amount >= 10 )
			$cell_id="vioR";
?>
<tr>
    <td ><a href="index.php?tab=violation-by-product&action=search&flag=1&field=sku&value=<?php echo $violator->sku; ?>&sku=<?php echo $violator->sku; ?>"><?php echo $violator->sku; ?></a></td>

        <td ><a href="index.php?&tab=violation-by-seller&action=search&flag=1&field=name&value=<?php echo $violator->name; ?>&website_id=<?php echo $violator->website_id; ?>"><?php echo $violator->name; ?></a></td>
    	<td><?php echo toMoney($violator->vendor_price); ?></td>
        <td><?php echo toMoney($violator->map_price) ;?></td>
      	<td id="<?php echo $cell_id; ?>"><?php echo toMoney($violator->violation_amount); ?></td>
         <td><a href="<?php echo $violator->website_product_url; ?>" target="_blank">View</a></td>
				
</tr>				
<?php } ?>
                  
</tbody></table> 

<?php
        if (count($violators_array) == 0) {
            ?><table class="GrayBlack" align="center">
            <tr align="center"><td width="500"> No Records Found  </td> </tr></table>
         <?php
        } ?>
<div class="cleaner" style="padding-top: 15px; ">

        </div>
 <div align="left" style="display:block; padding-top: 20px; " >
  <?php echo $pagination_html; ?>
</div> 

    </div>
     
     

<div  >
    <table>
        <tr>
            <td>
                <div style="clear:left; padding-top: 50px;  "> 
                <?php include_once 'charts/a1.php'; ?>
                    </div>
            </td>
        </tr>
        <tr>
            <td>
                <div style="float: left; padding-top:  50px; "> 
                <?php include_once 'charts/a2.php'; ?>
                     </div>
            </td>
        </tr>

    </table>
</div>  
            
 </div>