<div class="top-paneltab">Vendor Violations </div>
<div class=" divcc" ></div> 
<table class="table1" >
    <tr>
        <td>
            <div class="divt1">
                <input  class="vendor-violation-search search" placeholder="Enter Seller..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action'] == "search" && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller') echo $_GET['value']; ?>"
                        id="textBoxSearch"   /> 
            </div>
            <div class="divt22 search-btn-container">

                <button href="javascript:void(0);" class="btn-search"  onclick="search('.vendor-violation-search','name','search');" >Search</button>
            </div>
            <div class="divt22">

                <button href="javascript:void(0);" class="btn-search"  onclick="show_all();" >Show all</button>
            </div>
        </td>
        <td>
            <div class="divt22">

                <select  id="exportv" name="export_to" class="dropdown" title="Export">
                    <option value="csv" selected >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>
                </select>
            </div>
        </td>
        <td>
            <div class="divt22">
                <button href="" id="1" class="btn-search" onclick="exporttov();">Export</button>
            </div>
        </td>

        <td>
            <div class="results-per-page-block"  >
                <select name="vendor-limitv" class="results-per-page dropdown"  >
                    <option <?php echo  ($limit==15) ? "selected" : "" ;  ?> value="15">15</option>
                    <option  <?php echo  ($limit==25) ? "selected" : "" ;  ?> value="25">25</option>
                    <option  <?php echo  ($limit==50) ? "selected" : "" ;  ?>  value="50">50</option>
                    <option  <?php echo  ($limit==75) ? "selected" : "" ;  ?> value="75">75</option>
                    <option  <?php echo  ($limit==100) ? "selected" : "" ;  ?>  value="100">100</option>
                </select>
            </div>
        </td>
    </tr>
</table>






<div class="cleaner1" >
</div>
<table align="center">
    <tr>
        <td>
            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td>
                            Seller
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=name&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "name" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        </td>
                        <td>
                            Total Violations 
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=wi_count&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "wi_count" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        </td>	

                        <td>
                            Max Violation amount
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=maxvio&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "maxvio" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        </td>
                        <td>
                            Min Violation amount
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=minvio&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "minvio" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        </td>
                    </tr>

                    <?php
                
                    foreach ($page_violated_seller as $vendor) {

                        $vendor_link = "?tab=violation-by-seller&website_id=" . $vendor->website_id . "&wname=" . $vendor->name;
                        if (isset($_GET['page']) && $_GET['page']) { //adding pagination for first grid/table
                            $vendor_link.="&page=" . $_GET['page'];
                        }
                        if (isset($_GET['action']) && $_GET['action'] == "search") { //added that search  was included
                            $vendor_link.="&action=" . $_GET['action'] . "&field=website_id&value=" . $_GET['value'];
                        }
                        ?>

                        <tr>

                            <td><a href="<?php echo $vendor_link; ?>"> <?php echo $vendor->name; ?> </a></td>
                            <td><?php echo $vendor->wi_count; ?></td>
                            <td><?php echo "$" . $vendor->maxvio; ?></td>
                            <td><?php echo "$" . $vendor->minvio; ?></td>
                        </tr>
                    <?php } ?>

            </table>	
            <?php
        if (count($page_violated_seller) == 0) {
            ?><table class="GrayBlack" align="center">
            <tr align="center"><td width="500"> No Records Found  </td> </tr></table>
         <?php
        } ?>
        </td> </tr>       
</tbody></table> 
<div align="left" style="display:block; " >
     <?php echo $pagination_html; ?>
</div>
<div class="cleaner1" >

</div>
<div class="cleaner1" >

</div>
 
