<div class="tab-title"> Products Violated By <?php echo $violators_array3[0]->wname; ?> </div>

<table align="center"  width="1000px" >
    <tr>
        <td >
            <div class="divt1">

<input  class="vendor-violation-search2 search" placeholder="Enter SKU..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action']=="search2" && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller') echo $_GET['value']; ?>"  id="textBoxSearch" onkeyup="tableSearch.search(event);"   /> 
</div>
            <div class="divt2">
                <button href="javascript:void(0);" class="btn-search"  onclick="vendor_violation_search2();">Search</button>
            </div>
           
        </td>
        <td> 
            <div class="divt1">
                

                <select  id="exportv2" name="export_to"  class="dropdown" >
                   
                    <option value="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
            <div class="divt2">
                <button href="" id="1" class="btn-search" onclick="exporttov2();">Export</button>
            </div>
    </td>
</tr>
</table>
<!-- table part -->
<div class="cleaner1" >

</div>
<table align="center">
    <tr>
        <td>
            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td >SKU
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=sku&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="sku" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                           
                        </td>
                        <td >Vendor price
                        <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=vendor_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="vendor_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Map
                       <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=map_price&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="map_price" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                        <td >Violation amount
                     <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction=="asc"? "desc" : "asc")?>&sort=violation_amount&<?php echo  $page_param?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] :"" ); ?><?php echo $additional_params;?>" >
                           		<img  style="float:right;" width="22" src="img/arrow_<?php echo ( $order_field=="violation_amount" ? $direction : "asc" ); ?>_1.png" />
                           </a>
                        </td>
                       
                    </tr>
<?php     
      
if(count($violators_array)==0)
{  ?>
                    <tr align="center"><td> No Records Found  </td> </tr>
                    
                    <?php
}

	foreach ($violators_array as $violator) {
		
		$cell_id="vio";
		if ($violator->violation_amount >= 5 && $violator->violation_amount<10 )
			$cell_id="vioO";
		else if ($violator->violation_amount >= 10 )
			$cell_id="vioR";
?>
<tr>
    <td ><a href="index.php?tab=violation-by-product&action=searchfirst&flag=1&field=sku&value=<?php echo $violator->sku; ?>"><?php echo $violator->sku; ?></a></td>
<!--	<td><a href="index.php?tab=violation-by-product&action=searchfirstv1&field=sku&value=<?php //echo $violator->sku; ?>"><?php// echo $violator->sku; ?></a></td> -->
	<td><?php echo "$".$violator->vendor_price; ?></td>
	<td><?php echo "$".$violator->map_price; ?></td>
       <!-- <td><?php //echo money_format('$%i',$violator->map_price); ?></td> -->
	<td id="<?php echo $cell_id; ?>"><?php echo "$".$violator->violation_amount; ?></td>
				
</tr>				
<?php } ?>
                  
</tbody></table> 

</td>  
</tr>       
</table> 
<div align="left" style="display:block;" >
	<?php include ('page2.php'); ?>
</div>	
 
<div>
    <?php include_once 'charts/a4.php'; ?>
</div>

<script type="text/javascript">
function vendor_violation_search2() {
	var field = "sku";
	var value = $(".vendor-violation-search2").val();
                     
	var search_url_additional_params = "&website_id=<?php echo $website_id;  ?>";

	var search_link = "index.php?action=searchv2&field=" + field + "&value=" + value +"&tab=violation-by-seller"+ search_url_additional_params;
	window.open(search_link, "_self");
		tableSearch.runSearch();
}
                                           
function exporttov2(){
	var mode = $("#exportv2").val();
	var url_options= window.location.search.substring(1);
                                
	if (url_options.length)
		url_options='?'+url_options;
                        		
	if (mode)                                    
		open("export_vendor2_" + mode + ".php"+url_options);
}
</script>