
<div class="top-paneltab"> Products Violated By <?php echo $violators_array3[0]->wname; ?> </div>
<div class=" divcc" >
                &NonBreakingSpace;
            </div> 

<table align="center"  width="1000px" >
    <tr>
        <td >
            <div class="divt1">

                <input  class="vendor-violation-search2 search" placeholder="Enter SKU..." type="text" size="30"  maxlength="1000" value="<?php if (isset($_GET['action']) && $_GET['action'] == "search2" && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller') echo $_GET['value']; ?>"  id="textBoxSearch"    /> 
            </div>
            <div class="divt22">
                <button href="javascript:void(0);" class="btn-search"  onclick="search('.vendor-violation-search2','sku','search2');">Search</button>
            </div>
           <div class="divt22">

                <button href="javascript:void(0);" class="btn-search"  onclick="show_all();" >Show all</button>
            </div>
        </td>
        <td> 
            <div class="divt22">


                <select  id="exportv2" name="export_to"  class="dropdown" >

                    <option value="csv" selected  >Excel csv</option>
                    <option value="xls" >Excel xls</option>
                    <option value="pdf" >PDF</option>

                </select>
            </div>
            <div class="divt22">
                <button href="" id="1" class="btn-search" onclick="exporttov2();">Export</button>
            </div>
        </td>
        <td>
            <div class="results-per-page-block" style="float:left;padding-top:6px;" >
                <select name="vendor2-limitv2" class="results-per-page2 dropdown"  >
                   
                    <option <?php echo  ($limit==15) ? "selected" : "" ;   ?> value="15">15</option>
                    <option  <?php echo  ($limit==25) ? "selected" : "" ;   ?> value="25">25</option>
                    <option  <?php echo  ($limit==50) ? "selected" : "" ;   ?>  value="50">50</option>
                    <option  <?php echo  ($limit==75) ? "selected" : "" ;   ?> value="75">75</option>
                    <option  <?php echo  ($limit==100) ? "selected" : "" ;   ?>  value="100">100</option>
                </select>
            </div>
        </td>

    </tr>
</table>
<!-- table part -->
<div class="cleaner1" >

</div>
<table align="center">
    <tr>
        <td>
            <table class="GrayBlack" align="center">
                <tbody id="data">
                    <tr> 
                        <td >SKU
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=sku&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "sku" ? $direction : "asc" ); ?>_1.png" />
                            </a>

                        </td>
                        <td >Vendor price
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=vendor_price&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "vendor_price" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        </td>
                        <td >Map
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=map_price&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "map_price" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        </td>
                        <td >Violation amount
                            <a href="index.php?tab=<?php echo $tab_name; ?>&grid=vvendor_2&dir=<?php echo ($direction == "asc" ? "desc" : "asc") ?>&sort=violation_amount&<?php echo $page_param ?>=<?php echo $page ?><?php echo (isset($_GET['action']) && $_GET['action'] && isset($_GET['tab']) && $_GET['tab'] == 'violation-by-seller' ? "&action=" . $_GET['action'] . "&field=" . $_GET['field'] . "&value=" . $_GET['value'] : "" ); ?><?php echo $additional_params; ?>" >
                                <img  style="float:right;" width="22" src="images/arrow_<?php echo ( $order_field == "violation_amount" ? $direction : "asc" ); ?>_1.png" />
                            </a>
                        </td>

                    </tr>
                    <?php
                 

                    foreach ($violators_array as $violator) {

                        $cell_id = "vio";
                        if ($violator->violation_amount >= 5 && $violator->violation_amount < 10)
                            $cell_id = "vioO";
                        else if ($violator->violation_amount >= 10)
                            $cell_id = "vioR";
                        ?>
                        <tr>
                            <td ><a href="index.php?tab=violation-by-product&action=searchfirst&flag=1&field=sku&value=<?php echo $violator->sku; ?>"><?php echo $violator->sku; ?></a></td>
                        <!--	<td><a href="index.php?tab=violation-by-product&action=searchfirstv1&field=sku&value=<?php //echo $violator->sku;  ?>"><?php // echo $violator->sku;  ?></a></td> -->
                            <td><?php echo "$" . $violator->vendor_price; ?></td>
                            <td><?php echo "$" . $violator->map_price; ?></td>
                           <!-- <td><?php //echo money_format('$%i',$violator->map_price);  ?></td> -->
                            <td id="<?php echo $cell_id; ?>"><?php echo "$" . $violator->violation_amount; ?></td>

                        </tr>				
                    <?php } ?>

                </tbody></table> 
<?php
        if (count($violators_array) == 0) {
            ?><table class="GrayBlack" align="center">
            <tr align="center"><td width="500"> No Records Found  </td> </tr></table>
         <?php
        } ?>
        </td>  
    </tr>       
</table> 
<div align="left" style="display:block;" >
    <?php include ('page2.php'); ?>
</div>	
  <div  >
                &NonBreakingSpace;
            </div> 
<div class=" divcc" >
                &NonBreakingSpace;
            </div>  
<div>
    <?php include_once 'charts/a4.php'; ?>
</div>

<script type="text/javascript">
    function exporttov2() {
        var mode = $("#exportv2").val();
        var url_options = window.location.search.substring(1);

        if (url_options.length)
            url_options = '?' + url_options;

        if (mode)
            open("export/export_vendor2_" + mode + ".php" + url_options);
    }

 
</script>